networks:
  inception-network:
    name: inception-network
    driver: bridge

volumes:
  database:
    driver_opts:
      type: none
      o: bind
      device: /home/jbertin/data/database/
  website:
    driver_opts:
      type: none
      o: bind
      device: /home/jbertin/data/website/
  portainer:
    driver_opts:
      type: none
      o: bind
      device: /home/jbertin/data/portainer/
  ftp:
    driver_opts:
      type: none
      o: bind
      device: /home/jbertin/data/website/wordpress/

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - "website:/var/www/html"
    depends_on:
      - wordpress
    networks:
      - inception-network
    restart: always

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - "website:/var/www/html"
    depends_on:
      - mariadb
      - redis
    networks:
      - inception-network
    restart: always
    env_file: .env

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "database:/var/lib/mysql"
    networks:
      - inception-network
    restart: always
    env_file: .env

  redis:
    build: requirements/redis/
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - inception-network
    restart: always

  ftp-server:
    build: requirements/ftp-server/
    container_name: ftp-server
    ports:
      - "21:21"
    volumes:
      - ftp:/var/www/html/wordpress
    depends_on:
      - wordpress
    networks:
      - inception-network
    restart: always
    env_file: .env

  portainer:
    build: requirements/portainer/
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - portainer:/data
    depends_on:
      - wordpress
    networks:
      - inception-network
    restart: always

